name: frozit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  dotted_line: ^3.2.2
  chip_list: ^2.4.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf
        - asset: assets/fonts/AvenirLTStd-Black.otf
        - asset: assets/fonts/AvenirLTStd-Roman.otf
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf
        - asset: assets/fonts/Arial Bold.ttf
        - asset: assets/fonts/Arial Italic.ttf
        - asset: assets/fonts/Arial Bold Italic.ttf
